owner: MinecraftNTU
repo: service-status-monitor

sites:
  - name: Minecraft Creative Server（創造服）
    check: "tcp-ping"
    url: $CREATIVE_SERVER_IP
    port: $CREATIVE_SERVER_PORT
  - name: MyNTU Dashboard
    url: https://dashboard.myntu.me
  - name: Bluemine
    url: https://bluemine.myntu.me
  - name: MineNTU Landing Page
    url: https://minecraft.myntu.me
  - name: MineNTU Docs Page
    url: https://minecraft.myntu.me/docs
  - name: Service API
    url: $SERVICE_API_URL
  - name: Assistant Bot
    url: $ASSISTANT_BOT_URL

status-website:
  baseUrl: /status
  name: MineNTU 服務狀態
  introTitle: MineNTU 服務狀態

i18n:
  allSystemsOperational: 所有服務皆正常運作
  overallUptime: 在線率
  averageResponseTime: 平均伺服器回應時間
  liveStatus: 目前在線狀態
  ms: ms
  up: Up
  footer: THIS PAGE IS NOT FULLY OPTIMIZED.
