owner: MinecraftNTU
repo: service-status-monitor

sites:
  - name: MineNTU Service API
    url: $SERVICE_API_URL
  - name: MineNTU Landing Page
    url: https://minecraft.myntu.me
  - name: MineNTU Docs Page
    url: https://minecraft.myntu.me/docs
  - name: MineNTU Assistant Bot
    url: $ASSISTANT_BOT_URL

status-website:
  introTitle: MineNTU 各服務狀態
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/84632044
  name: 服務狀態 - MineNTU 臺大麥塊
  themeUrl: https://minecraft.myntu.me/status/ocean.css
